Repository Jesuitman/m3-H8rAid, pull requests merged in 2023-12, with the labels that each got.

#16 add domPurify to package json and different search and filter logic
  package-lock.json
  package.json
  src/Card/Card.js
  src/Search/Search.js
Labels: documentation, enhancement, user story

#19 fix a tag links to append wiki to url
  src/Card/Card.js
  src/hooks/modifyRelativeUrls.js
Labels: documentation, enhancement

#20 add compression for cards as well as header
  src/App/App.css
  src/App/App.js
  src/Card/Card.js
Labels: enhancement, dev task
