Repository Jesuitman/m3-H8rAid, pull requests merged in 2024-01, with the labels that each got.

#28 Feat/styling
  public/index.html
  src/App/App.css
  src/Card/Card.css
  src/Card/Card.js
  src/Search/Search.css
  src/Search/Search.js
  src/WikipediaPage/WikipediaPage.css
  src/index.css
Labels: enhancement, dev task

#30 Feature/random controversy
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.js
  src/Card/Card.test.js
  src/Favorites/Favorites.test.js
  src/Main/Main.test.js
  src/Search/Search.js
  src/Search/Search.test.js
  src/WikipediaPage/WikipediaPage.test.js
  src/hooks/useSearchResults.js
Labels: enhancement, dev task

#29 feat/auth0 integration
  .env
  package-lock.json
  package.json
  src/App/App.js
  src/Main/Main.js
  src/Search/Search.js
  src/index.js
Labels: enhancement, dev task

#31 Fix/render logic order
  src/App/App.js
  src/Search/Search.js
Labels: bug

#32 fix/delete .env from github
  .env
  .gitignore
  src/Main/Main.js
  src/index.js
Labels: bug, dev task

#35 Test/profiletest
  src/App/App.css
  src/App/App.js
  src/Card/Card.js
  src/Search/Search.css
  src/Search/Search.js
  src/UserView/UserView.js
  src/savedIdeasvar.js
Labels: bug, enhancement, dev task

#38 Cleanup/finderror
  src/App/App.js
  src/Search/Search.js
  src/UserView/UserView.js
  src/logo.svg
Labels: enhancement, dev task

#41 Feature/test accessibility
  src/App/App.css
  src/App/App.js
  src/Card/Card.css
  src/Search/Search.js
  src/hooks/useSearchResults.js
Labels: extension

#44 Styling/userview
  cypress/e2e/spec.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/sampleRandomCards.json
  cypress/fixtures/wikipediaApiResponse.json
  src/App/App.js
  src/Card/Card.js
  src/Errors/ErrorBoundary.js
  src/Errors/Errors.js
  src/Main/Main.css
  src/UserView/UserView.css
  src/UserView/UserView.js
Labels: enhancement, extension, dev task
